<a href="https://colab.research.google.com/github/mariokart345/DS-Unit-1-Sprint-3-Linear-Algebra/blob/master/module4-linear-algebra/LS_DS_134_Linear_Algebra_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Objectives:
- define a vector and calculate a vector length and dot product
- define a matrix and calculate a matrix dot product, transpose, and inverse
- explain cosine similarity and compute the similarity between two vectors
- use linear algebra to solve for linear regression coefficients

#Use the following information to answer the assignment questions 1) - 11).

###Is head size related to brain weight in healthy adult humans?

The Brainhead.csv dataset provides information on 237 individuals who were subject to post-mortem examination at the Middlesex Hospital in London around the turn of the 20th century. Study authors used cadavers to see if a relationship between brain weight and other more easily measured physiological characterizes such as age, sex, and head size could be determined. The end goal was to develop a way to estimate a person’s brain size while they were still alive (as the living aren’t keen on having their brains taken out and weighed). 

**We wish to determine if we can improve on our model of the linear relationship between head size and brain weight in healthy human adults.**

Source: R.J. Gladstone (1905). "A Study of the Relations of the Brain to the Size of the Head", Biometrika, Vol. 4, pp105-123.

In [19]:
#Import the Brainhead.csv dataset from a URL and print the first few rows
import pandas as pd
import numpy as np
data_url = 'https://raw.githubusercontent.com/LambdaSchool/data-science-practice-datasets/main/unit_1/Brainhead/Brainhead.csv'
df = pd.read_csv(data_url, skipinitialspace=True, header=0)
df.head()

Gender  Age  Head  Brain
0       1    1  4512   1530
1       1    1  3738   1297
2       1    1  4261   1335
3       1    1  3777   1282
4       1    1  4177   1590

1) Store the response variable - brain size - as a matrix called Y.

In [13]:
Y = np.array(df['Brain']).reshape(-1,1)
Y[0:5]

array([[1530],
       [1297],
       [1335],
       [1282],
       [1590]])

2) Store the explanatory variable - head size size - as a matrix called X.  Don't forget to include the column of 1s for the intercept term.

In [14]:
one = np.repeat(1,len(df)).reshape(-1,1)
X = np.concatenate((one,np.array(df['Head']).reshape(-1,1)),axis=1)
X[0:5]

array([[   1, 4512],
       [   1, 3738],
       [   1, 4261],
       [   1, 3777],
       [   1, 4177]])

3) Calculate $X^T$.  Explain what the transpose of a matrix is.

In [4]:
X_T = np.transpose(X)

Answer: The transpose of a matrix is 

4) Use matrix multplication to calculate $X^TX$

In [15]:
X_T_X = np.matmul(X_T,X)

5) Calculate $(X^TX)^{-1}$.  Explain what the inverse of a matrix is.

In [16]:
X_T_X_inv = np.linalg.inv(X_T_X)

Answer: 

6) Use matrix multiplication to calculate $X^TY$.

In [17]:
X_T_Y = np.matmul(X_T,Y)

7) Use your previous results to calculate the values of the slope and intercept using the formula $$ B = (X^{'}X)^{-1}X^{'}Y$$

In [18]:
B=np.matmul(X_T_X_inv,X_T_Y)
B

array([[3.25573421e+02],
       [2.63429339e-01]])

8) Use the OLS function to calculate the slope and intercept and compare your answers.

In [11]:
from statsmodels.formula.api import ols
model = ols('Head ~ Brain',data=df).fit()
print(model.params)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Intercept    520.610141
Brain          2.426881
dtype: float64


9) Create a new X matrix that includes columns for both head size and age group.

11) Calculate the values of the intercept and slope terms for head size and age using the formula $$ B = (X^{'}X)^{-1}X^{'}Y$$

11) Use the OLS function to confirm your answer in 10).

In [ ]:
### YOUR CODE HERE ###

#Use the following information to answer the assignment questions 12) - 16).

The song writing collaboration between John Lennon and Paul McCartney was one of the most productive in music history.  Unlike many other partnerships where one individual wrote lyrics and one wrote music, Lennon and McCartney composed both, and it was decided that any song that was written would be credited to both.  In the beginning of their relationship, many of their songs were truly collabroative.  However, later on, they often worked separately with little to no input from the other.    

Because of extensive reporting on the Beatles over the years, it is generally known if a Lennon-McCartney song was a true collabortion, primarily (or totally) writen by Lennon, or primarily (or totally) written by McCartney.  

However, there are several disputed songs where both Lennon and McCartney at times claimed to be the sole (or primary) composer.

We will now use cosine similarity to determine if *Ticket to Ride* (disputed) is most similar to *From Me to You* (collabortive, not disputed) or *Strawberry Fields* (Lennon, not disputed).

From the Wikipedia article on the Lennon-McCartney Partnership: Lennon said that McCartney's contribution was limited to "the way Ringo played the drums".In Many Years from Now, McCartney said "we sat down and wrote it together ... give him 60 percent of it."

12) Import the text of Strawberry Fields and calculate the freqency of song lyrics using the code below.

In [ ]:
### YOUR CODE HERE ###


13) Import the text of From Me to You and calculate the freqency of song lyrics using the code below.

In [ ]:
### YOUR CODE HERE ###

13) Import the text of Ticket to Ride using the code below.

In [ ]:
### YOUR CODE HERE ###


14) Concatenate Ticket to Ride and Strawberry Fields and calculate the cosine similarity.

In [ ]:
### YOUR CODE HERE ###



15) Concatenate Ticket to Ride and From Me to You and calculate the cosine similarity.

In [ ]:
### YOUR CODE HERE ###



16) What is your conclusion about Ticket to Ride?  Does it appear most similar to Strawberry Fields (Lennon) or From Me to You (collaborative)?

Answer: 