<a href="https://colab.research.google.com/github/mariokart345/DS-Unit-1-Sprint-3-Linear-Algebra/blob/master/module4-linear-algebra/LS_DS_134_Linear_Algebra_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Objectives:
- define a vector and calculate a vector length and dot product
- define a matrix and calculate a matrix dot product, transpose, and inverse
- explain cosine similarity and compute the similarity between two vectors
- use linear algebra to solve for linear regression coefficients

#Use the following information to answer the assignment questions 1) - 11).

###Is head size related to brain weight in healthy adult humans?

The Brainhead.csv dataset provides information on 237 individuals who were subject to post-mortem examination at the Middlesex Hospital in London around the turn of the 20th century. Study authors used cadavers to see if a relationship between brain weight and other more easily measured physiological characterizes such as age, sex, and head size could be determined. The end goal was to develop a way to estimate a person’s brain size while they were still alive (as the living aren’t keen on having their brains taken out and weighed). 

**We wish to determine if we can improve on our model of the linear relationship between head size and brain weight in healthy human adults.**

Source: R.J. Gladstone (1905). "A Study of the Relations of the Brain to the Size of the Head", Biometrika, Vol. 4, pp105-123.

In [1]:
#Import the Brainhead.csv dataset from a URL and print the first few rows
import pandas as pd
import numpy as np
data_url = 'https://raw.githubusercontent.com/LambdaSchool/data-science-practice-datasets/main/unit_1/Brainhead/Brainhead.csv'
df = pd.read_csv(data_url, skipinitialspace=True, header=0)
df.head()

Gender  Age  Head  Brain
0       1    1  4512   1530
1       1    1  3738   1297
2       1    1  4261   1335
3       1    1  3777   1282
4       1    1  4177   1590

1) Store the response variable - brain size - as a matrix called Y.

In [2]:
Y = np.array(df['Brain']).reshape(-1,1)
Y[0:5]

array([[1530],
       [1297],
       [1335],
       [1282],
       [1590]])

2) Store the explanatory variable - head size size - as a matrix called X.  Don't forget to include the column of 1s for the intercept term.

In [3]:
one = np.repeat(1,len(df)).reshape(-1,1)
head = np.array(df['Head']).reshape(-1,1)
X = np.concatenate((one,head),axis=1)
X[0:5]

array([[   1, 4512],
       [   1, 3738],
       [   1, 4261],
       [   1, 3777],
       [   1, 4177]])

3) Calculate $X^T$.  Explain what the transpose of a matrix is.

In [4]:
X_T = np.transpose(X)

Answer: The transpose of a matrix is 

4) Use matrix multplication to calculate $X^TX$

In [5]:
X_T_X = np.matmul(X_T,X)

5) Calculate $(X^TX)^{-1}$.  Explain what the inverse of a matrix is.

In [6]:
X_T_X_inv = np.linalg.inv(X_T_X)

Answer: 

6) Use matrix multiplication to calculate $X^TY$.

In [7]:
X_T_Y = np.matmul(X_T,Y)

7) Use your previous results to calculate the values of the slope and intercept using the formula $$ B = (X^{'}X)^{-1}X^{'}Y$$

In [8]:
B=np.matmul(X_T_X_inv,X_T_Y)
B

array([[3.25573421e+02],
       [2.63429339e-01]])

8) Use the OLS function to calculate the slope and intercept and compare your answers.

In [9]:
from statsmodels.formula.api import ols
model = ols('Head ~ Brain',data=df).fit()
print(model.params)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Intercept    520.610141
Brain          2.426881
dtype: float64


9) Create a new X matrix that includes columns for both head size and age group.

In [10]:
df['Age']=df['Age']-1

In [11]:
age = np.array(df['Age']).reshape(-1,1)

In [12]:
X = np.concatenate((one, head, age),axis=1)

11) Calculate the values of the intercept and slope terms for head size and age using the formula $$ B = (X^{'}X)^{-1}X^{'}Y$$

In [13]:
X_T = np.transpose(X)
X_T_X = np.matmul(X_T,X)
X_T_X_inv = np.linalg.inv(X_T_X)
X_T_Y = np.matmul(X_T,Y)
B=np.matmul(X_T_X_inv,X_T_Y)
B

array([[ 3.47550501e+02],
       [ 2.60438766e-01],
       [-2.07316446e+01]])

11) Use the OLS function to confirm your answer in 10).

In [14]:
model = ols('Brain ~ Head + Age',data=df).fit()
print(model.params)

Intercept    347.550501
Head           0.260439
Age          -20.731645
dtype: float64


#Use the following information to answer the assignment questions 12) - 16).

The song writing collaboration between John Lennon and Paul McCartney was one of the most productive in music history.  Unlike many other partnerships where one individual wrote lyrics and one wrote music, Lennon and McCartney composed both, and it was decided that any song that was written would be credited to both.  In the beginning of their relationship, many of their songs were truly collabroative.  However, later on, they often worked separately with little to no input from the other.    

Because of extensive reporting on the Beatles over the years, it is generally known if a Lennon-McCartney song was a true collabortion, primarily (or totally) writen by Lennon, or primarily (or totally) written by McCartney.  

However, there are several disputed songs where both Lennon and McCartney at times claimed to be the sole (or primary) composer.

We will now use cosine similarity to determine if *Ticket to Ride* (disputed) is most similar to *From Me to You* (collabortive, not disputed) or *Strawberry Fields* (Lennon, not disputed).

From the Wikipedia article on the Lennon-McCartney Partnership: Lennon said that McCartney's contribution was limited to "the way Ringo played the drums".In Many Years from Now, McCartney said "we sat down and wrote it together ... give him 60 percent of it."

12) Import the text of Strawberry Fields and calculate the freqency of song lyrics using the code below.

In [15]:
Strawberry_Fields = "let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever living is easy with eyes closed misunderstanding all you see its getting hard to be someone but it all works out it doesnt matter much to me let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever no one I think is in my tree I mean it must be high or low that is you cant you know tune in but its all right that is I think its not too bad let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever always no sometimes think but you know I know when it's a dream I think er no I mean er yes but its all wrong that is I think I disagree let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever Strawberry Fields forever Strawberry Fields forever"
Strawberry_df = pd.DataFrame({"Words": Strawberry_Fields.split()})
Strawberry_df_Freq = pd.DataFrame(pd.crosstab(index=Strawberry_df['Words'],columns=['count']))
Strawberry_df_Freq[0:10]

col_0       count
Words            
Fields         10
I               8
Im              4
Strawberry     10
a               1
about           4
all             4
always          1
and             4
bad             1

13) Import the text of From Me to You and calculate the freqency of song lyrics using the code below.

In [16]:
From_Me = "if there's anything that you want if there's anything I can do just call on me and Ill send it along with love from me to you Ive got everything that you want like a heart thats oh so true just call on me and Ill send it along with love from me to you Ive got arms that long to hold you and keep you by my side Ive got lips that long to kiss you and keep you satisfied oh if theres anything that you want if theres anything I can do just call on me and Ill send it along with love from me to you from me to you just call on me and Ill send it along with love from me to you Ive got arms that long to hold you and keep you by my side Ive got lips that long to kiss you and keep you satisfied oh if theres anything that you want if theres anything I can do just call on me and Ill send it along with love from me to you to you to you to you"
From_Me_df = pd.DataFrame({"Words":From_Me.split()})
From_Me_Freq = pd.DataFrame(pd.crosstab(index=From_Me_df['Words'],columns=['count']))
From_Me_Freq[0:10]

col_0     count
Words          
I             3
Ill           5
Ive           5
a             1
along         5
and           9
anything      6
arms          2
by            2
call          5

13) Import the text of Ticket to Ride using the code below.

In [17]:
Ticket_To = "I think Im gonna be sad I think its today yeah the girl thats driving me mad is going away shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care she said that living with me is bringing her down yeah for she would never be free when I was around shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care I dont know why shes ridin so high she ought to think twice she ought to do right by me before she gets to saying goodbye she ought to think twice she ought to do right by me I think Im gonna be sad I think its today yeah the girl thats driving me mad is going away yeah shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care I dont know why shes ridin so high she ought to think twice she ought to do right by me before she gets to saying goodbye she ought to think twice she ought to do right by me she said that living with me is bringing her down yeah for she would never be free when I was around ah shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care my baby dont care my baby dont care my baby dont care my baby dont care my baby dont care my baby dont care"
Ticket_To_df = pd.DataFrame({'Words':Ticket_To.split()})
Ticket_To_Freq = pd.DataFrame(pd.crosstab(index=Ticket_To_df['Words'],columns=['count']))
Ticket_To_Freq[0:10]

col_0     count
Words          
I             8
Im            2
a            12
ah            1
around        2
away          2
baby          6
be            4
before        2
bringing      2

14) Concatenate Ticket to Ride and Strawberry Fields and calculate the cosine similarity.

In [18]:
from numpy import dot
from numpy.linalg import norm
Songs = [Strawberry_df_Freq,Ticket_To_Freq]
All_Word_Count = pd.concat(Songs,axis=1)
All_Word_Count.fillna(0,inplace=True)
All_Word_Count.columns  = ['Strawberry Fields','Ticket To Ride']
cos_sim = dot(All_Word_Count['Strawberry Fields'], All_Word_Count['Ticket To Ride'])/(norm(All_Word_Count['Strawberry Fields'])*norm(All_Word_Count['Ticket To Ride']))
print(cos_sim)

0.324035859004908


15) Concatenate Ticket to Ride and From Me to You and calculate the cosine similarity.

In [19]:
Songs = [Ticket_To_Freq,From_Me_Freq]
All_Word_Count = pd.concat(Songs,axis=1)
All_Word_Count.fillna(0,inplace=True)
All_Word_Count.columns  = ['Ticket To Ride','From Me to You']
cos_sim = dot(All_Word_Count['Ticket To Ride'], All_Word_Count['From Me to You'])/(norm(All_Word_Count['Ticket To Ride'])*norm(All_Word_Count['From Me to You']))
print(cos_sim)

0.2882268853551227


16) What is your conclusion about Ticket to Ride?  Does it appear most similar to Strawberry Fields (Lennon) or From Me to You (collaborative)?

Answer: According to the cosine simularity tests, Ticket To Ride is most similar to Strawberry Fields written by Lennon.